spring:
  application:
    name: demo-spring-cloud-vault-transit
  profiles:
    active: demo

  datasource:
    url: jdbc:h2:mem:${db.name}
    username: ${db.username}
    password: ${db.password}
  h2:
    console:
      enabled: true
  
  config:
    import: vault://
  cloud:
    vault:
      enabled: true
      application-name: spring-cloud-vault
      host: localhost
      port: 8200
      scheme: http
      token: s.9DnSsGSceorKLGtD7EINh18M
      kv:
        transit-encrypted: true
    config:
      lifecycle:
        enabled: true
        min-renewal: 20s
        expiry-threshold: 1m
