spring:
  application:
    name: demo-spring-cloud-vault-transit
  
  config:
    import: vault://
  cloud:
    vault:
      enabled: true
      application-name: spring-cloud-vault
      uri: http://localhost:8200
      token: s.FZTp0c0fJV1D05D1qYDZsAtM
      kv:
        transit-encrypted: true
        transit-path: transit
        transit-key-name: spring-cloud-vault
        post-decrypt-mappings:
          db.name: h2database.name
          db.username: h2database.username
          db.password: h2database.password

management:
  endpoints:
    web:
      exposure:
        include: "*"
