spring:
  application:
    name: demo-spring-cloud-vault-transit
  profiles:
    active: DEV
  
  config:
    import: vault://
  cloud:
    vault:
      enabled: true
      application-name: ttl/mobius/core
      uri: https://vault.mobius.aliyun.sdecloud.tech
      token: s.K7DhPAE3azrvQ7rvfdHG3VmJ
      kv:
        transit-encrypted: true
        transit-path: transit
        transit-key-name: encryptor
        post-decrypt-mappings:
          db.username: tidb.username
          db.password: tidb.password
          redis.password: cache.password

management:
  endpoints:
    web:
      exposure:
        include: "*"
